// Auto-generated by demo/web/scripts/prepare_idrid_samples.py.
// Edit the script and re-run; do not modify this file by hand.
// Source: IDRiD (CC-BY-4.0) — Localization sub-challenge.
// Synthetic bilateral patients (one left + one right eye, same grade).
// Each eye carries GROUND-TRUTH od_center / fovea_center (display-frame
// pixels) so the demo overlays real markers, not detector estimates.
// 20 patients (40 images).

export const IDRID_PATIENTS = [
  {
    "patient": "p01",
    "grade": 0,
    "left": {
      "id": "IDRiD_p01_L_029_test",
      "orig_id": "IDRiD_029",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr0/IDRiD_p01_L_029_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p01_L_029_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        123.0,
        168.5
      ],
      "fovea_center": [
        286.2,
        188.2
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p01_R_037_test",
      "orig_id": "IDRiD_037",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr0/IDRiD_p01_R_037_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p01_R_037_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        395.5,
        193.1
      ],
      "fovea_center": [
        251.3,
        212.8
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p02",
    "grade": 0,
    "left": {
      "id": "IDRiD_p02_L_030_test",
      "orig_id": "IDRiD_030",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr0/IDRiD_p02_L_030_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p02_L_030_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        128.7,
        167.6
      ],
      "fovea_center": [
        279.0,
        189.6
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p02_R_039_test",
      "orig_id": "IDRiD_039",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr0/IDRiD_p02_R_039_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p02_R_039_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        341.3,
        211.5
      ],
      "fovea_center": [
        178.4,
        226.3
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p03",
    "grade": 0,
    "left": {
      "id": "IDRiD_p03_L_038_test",
      "orig_id": "IDRiD_038",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr0/IDRiD_p03_L_038_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p03_L_038_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        114.9,
        171.2
      ],
      "fovea_center": [
        273.8,
        183.3
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p03_R_043_test",
      "orig_id": "IDRiD_043",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr0/IDRiD_p03_R_043_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p03_R_043_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        318.4,
        137.7
      ],
      "fovea_center": [
        157.9,
        143.0
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p04",
    "grade": 0,
    "left": {
      "id": "IDRiD_p04_L_041_test",
      "orig_id": "IDRiD_041",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr0/IDRiD_p04_L_041_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p04_L_041_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        138.6,
        179.7
      ],
      "fovea_center": [
        284.1,
        194.5
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p04_R_054_test",
      "orig_id": "IDRiD_054",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr0/IDRiD_p04_R_054_test.jpg",
      "mask": "datasets/idrid/samples/dr0/IDRiD_p04_R_054_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        340.4,
        168.1
      ],
      "fovea_center": [
        181.6,
        184.2
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p05",
    "grade": 1,
    "left": {
      "id": "IDRiD_p05_L_021_train",
      "orig_id": "IDRiD_021",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr1/IDRiD_p05_L_021_train.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p05_L_021_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        80.5,
        137.7
      ],
      "fovea_center": [
        227.7,
        161.0
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p05_R_063_test",
      "orig_id": "IDRiD_063",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr1/IDRiD_p05_R_063_test.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p05_R_063_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        337.3,
        176.6
      ],
      "fovea_center": [
        179.8,
        185.6
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p06",
    "grade": 1,
    "left": {
      "id": "IDRiD_p06_L_073_test",
      "orig_id": "IDRiD_073",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr1/IDRiD_p06_L_073_test.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p06_L_073_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        96.1,
        180.2
      ],
      "fovea_center": [
        244.2,
        186.4
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p06_R_085_test",
      "orig_id": "IDRiD_085",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr1/IDRiD_p06_R_085_test.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p06_R_085_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        367.6,
        192.2
      ],
      "fovea_center": [
        225.0,
        191.8
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p07",
    "grade": 1,
    "left": {
      "id": "IDRiD_p07_L_074_test",
      "orig_id": "IDRiD_074",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr1/IDRiD_p07_L_074_test.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p07_L_074_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        118.4,
        192.2
      ],
      "fovea_center": [
        271.5,
        202.5
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p07_R_101_test",
      "orig_id": "IDRiD_101",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr1/IDRiD_p07_R_101_test.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p07_R_101_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        346.3,
        202.5
      ],
      "fovea_center": [
        199.9,
        220.4
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p08",
    "grade": 1,
    "left": {
      "id": "IDRiD_p08_L_079_train",
      "orig_id": "IDRiD_079",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr1/IDRiD_p08_L_079_train.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p08_L_079_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        82.6,
        141.7
      ],
      "fovea_center": [
        238.0,
        168.5
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p08_R_105_train",
      "orig_id": "IDRiD_105",
      "split": "train",
      "side": "right",
      "image": "datasets/idrid/samples/dr1/IDRiD_p08_R_105_train.jpg",
      "mask": "datasets/idrid/samples/dr1/IDRiD_p08_R_105_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        356.5,
        162.7
      ],
      "fovea_center": [
        205.7,
        162.3
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p09",
    "grade": 2,
    "left": {
      "id": "IDRiD_p09_L_003_train",
      "orig_id": "IDRiD_003",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr2/IDRiD_p09_L_003_train.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p09_L_003_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        93.0,
        151.5
      ],
      "fovea_center": [
        251.8,
        161.3
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p09_R_009_test",
      "orig_id": "IDRiD_009",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr2/IDRiD_p09_R_009_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p09_R_009_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        387.0,
        190.0
      ],
      "fovea_center": [
        240.1,
        199.4
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p10",
    "grade": 2,
    "left": {
      "id": "IDRiD_p10_L_008_test",
      "orig_id": "IDRiD_008",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr2/IDRiD_p10_L_008_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p10_L_008_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        106.9,
        155.1
      ],
      "fovea_center": [
        263.0,
        177.1
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p10_R_010_test",
      "orig_id": "IDRiD_010",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr2/IDRiD_p10_R_010_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p10_R_010_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        352.0,
        197.6
      ],
      "fovea_center": [
        211.1,
        211.5
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p11",
    "grade": 2,
    "left": {
      "id": "IDRiD_p11_L_011_test",
      "orig_id": "IDRiD_011",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr2/IDRiD_p11_L_011_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p11_L_011_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        104.1,
        165.4
      ],
      "fovea_center": [
        241.1,
        194.5
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p11_R_015_test",
      "orig_id": "IDRiD_015",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr2/IDRiD_p11_R_015_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p11_R_015_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        367.3,
        177.1
      ],
      "fovea_center": [
        233.4,
        188.2
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p12",
    "grade": 2,
    "left": {
      "id": "IDRiD_p12_L_012_test",
      "orig_id": "IDRiD_012",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr2/IDRiD_p12_L_012_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p12_L_012_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        77.3,
        137.2
      ],
      "fovea_center": [
        222.7,
        173.0
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p12_R_017_test",
      "orig_id": "IDRiD_017",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr2/IDRiD_p12_R_017_test.jpg",
      "mask": "datasets/idrid/samples/dr2/IDRiD_p12_R_017_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        392.4,
        157.7
      ],
      "fovea_center": [
        241.9,
        196.3
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p13",
    "grade": 3,
    "left": {
      "id": "IDRiD_p13_L_002_train",
      "orig_id": "IDRiD_002",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr3/IDRiD_p13_L_002_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p13_L_002_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        112.6,
        133.6
      ],
      "fovea_center": [
        271.0,
        158.7
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p13_R_001_train",
      "orig_id": "IDRiD_001",
      "split": "train",
      "side": "right",
      "image": "datasets/idrid/samples/dr3/IDRiD_p13_R_001_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p13_R_001_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        341.3,
        215.5
      ],
      "fovea_center": [
        178.4,
        235.2
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p14",
    "grade": 3,
    "left": {
      "id": "IDRiD_p14_L_004_train",
      "orig_id": "IDRiD_004",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr3/IDRiD_p14_L_004_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p14_L_004_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        154.3,
        153.3
      ],
      "fovea_center": [
        319.9,
        173.5
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p14_R_006_test",
      "orig_id": "IDRiD_006",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr3/IDRiD_p14_R_006_test.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p14_R_006_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        353.8,
        179.2
      ],
      "fovea_center": [
        208.4,
        188.7
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p15",
    "grade": 3,
    "left": {
      "id": "IDRiD_p15_L_007_test",
      "orig_id": "IDRiD_007",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr3/IDRiD_p15_L_007_test.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p15_L_007_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        100.5,
        164.1
      ],
      "fovea_center": [
        276.4,
        179.7
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p15_R_009_train",
      "orig_id": "IDRiD_009",
      "split": "train",
      "side": "right",
      "image": "datasets/idrid/samples/dr3/IDRiD_p15_R_009_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p15_R_009_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        366.8,
        138.5
      ],
      "fovea_center": [
        229.5,
        166.7
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p16",
    "grade": 3,
    "left": {
      "id": "IDRiD_p16_L_011_train",
      "orig_id": "IDRiD_011",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr3/IDRiD_p16_L_011_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p16_L_011_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        126.9,
        158.7
      ],
      "fovea_center": [
        290.3,
        178.9
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p16_R_013_train",
      "orig_id": "IDRiD_013",
      "split": "train",
      "side": "right",
      "image": "datasets/idrid/samples/dr3/IDRiD_p16_R_013_train.jpg",
      "mask": "datasets/idrid/samples/dr3/IDRiD_p16_R_013_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        333.3,
        171.2
      ],
      "fovea_center": [
        184.2,
        180.7
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p17",
    "grade": 4,
    "left": {
      "id": "IDRiD_p17_L_001_test",
      "orig_id": "IDRiD_001",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr4/IDRiD_p17_L_001_test.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p17_L_001_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        77.7,
        173.5
      ],
      "fovea_center": [
        228.5,
        193.1
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p17_R_002_test",
      "orig_id": "IDRiD_002",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr4/IDRiD_p17_R_002_test.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p17_R_002_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        377.1,
        152.8
      ],
      "fovea_center": [
        229.5,
        175.3
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p18",
    "grade": 4,
    "left": {
      "id": "IDRiD_p18_L_003_test",
      "orig_id": "IDRiD_003",
      "split": "test",
      "side": "left",
      "image": "datasets/idrid/samples/dr4/IDRiD_p18_L_003_test.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p18_L_003_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        131.5,
        164.1
      ],
      "fovea_center": [
        306.4,
        190.0
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p18_R_004_test",
      "orig_id": "IDRiD_004",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr4/IDRiD_p18_R_004_test.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p18_R_004_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        344.0,
        170.7
      ],
      "fovea_center": [
        186.5,
        185.1
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p19",
    "grade": 4,
    "left": {
      "id": "IDRiD_p19_L_005_train",
      "orig_id": "IDRiD_005",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr4/IDRiD_p19_L_005_train.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p19_L_005_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        123.8,
        143.0
      ],
      "fovea_center": [
        267.9,
        167.6
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p19_R_005_test",
      "orig_id": "IDRiD_005",
      "split": "test",
      "side": "right",
      "image": "datasets/idrid/samples/dr4/IDRiD_p19_R_005_test.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p19_R_005_test_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        339.1,
        140.3
      ],
      "fovea_center": [
        209.8,
        156.4
      ],
      "od_radius": 28.4
    }
  },
  {
    "patient": "p20",
    "grade": 4,
    "left": {
      "id": "IDRiD_p20_L_006_train",
      "orig_id": "IDRiD_006",
      "split": "train",
      "side": "left",
      "image": "datasets/idrid/samples/dr4/IDRiD_p20_L_006_train.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p20_L_006_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        71.9,
        164.5
      ],
      "fovea_center": [
        232.1,
        185.6
      ],
      "od_radius": 28.4
    },
    "right": {
      "id": "IDRiD_p20_R_007_train",
      "orig_id": "IDRiD_007",
      "split": "train",
      "side": "right",
      "image": "datasets/idrid/samples/dr4/IDRiD_p20_R_007_train.jpg",
      "mask": "datasets/idrid/samples/dr4/IDRiD_p20_R_007_train_mask.png",
      "width": 512,
      "height": 340,
      "od_center": [
        408.4,
        168.5
      ],
      "fovea_center": [
        246.4,
        162.3
      ],
      "od_radius": 28.4
    }
  }
];
