// src/tabs/Demo.js — Live inference demo page.
// Lets the user supply up to two fundus images (left + right eye) of one
// patient, runs a simulated Config-D-style prediction in the browser, and lets
// the user confirm or reject the result. Confirmed / corrected cases are
// appended to a local relabeling buffer that can be exported as JSONL for
// further training.

import { useEffect, useMemo, useRef, useState } from 'react';
import { C, CONFIGS } from '../data';
import { Sec, Note } from '../components';
import { useLang } from '../i18n';
import { IDRID_PATIENTS } from './_idridSamples';
import { matchIdridUpload } from './_idridUpload';
import { analyzeFundus } from './_analyzeFundus';
import { predictPatient, getHealth, getPassword, setPassword, verifyPassword } from './_apiPredict';
import VisionWidget from './_VisionWidget';
import LiveVisualizationBlock from './_LiveGradcam';

// ---------------------------------------------------------------------------
// Walk-through cases that share an image with the preprocessing-pipeline
// gallery. Each entry exposes pre-generated Grad-CAM heatmap + attention
// overlay rendered by `demo/web/public/pipeline/helpers/s8_results.py` (proxy
// heatmap derived from flat-field anomaly detection; not a real Grad-CAM
// from a trained checkpoint).
// ---------------------------------------------------------------------------
const WALKTHROUGH_POOL = [
  { id: 'walk_dr00', grade: 0, left: 'pipeline/dr00/input/left.png', right: 'pipeline/dr00/input/right.png', explainable: true, resultsBase: 'pipeline/dr00/results' },
  { id: 'walk_dr01', grade: 1, left: 'pipeline/dr01/input/left.png', right: 'pipeline/dr01/input/right.png', explainable: true, resultsBase: 'pipeline/dr01/results' },
  { id: 'walk_dr02', grade: 2, left: 'pipeline/dr02/input/left.png', right: 'pipeline/dr02/input/right.png', explainable: true, resultsBase: 'pipeline/dr02/results' },
  { id: 'walk_dr03', grade: 3, left: 'pipeline/dr03/input/left.png', right: 'pipeline/dr03/input/right.png', explainable: true, resultsBase: 'pipeline/dr03/results' },
  { id: 'walk_dr04', grade: 4, left: 'pipeline/dr04/input/left.png', right: 'pipeline/dr04/input/right.png', explainable: true, resultsBase: 'pipeline/dr04/results' },
];

// ---------------------------------------------------------------------------
// IDRiD localization pool for the Random button. Unlike EyePACS, IDRiD ships
// pixel-accurate GROUND-TRUTH optic-disc + fovea centres (Localization
// sub-challenge), sourced from `_idridSamples.js`
// (regenerated by `demo/web/scripts/prepare_idrid_samples.py`).
//
// IDRiD is monocular, so each entry is a SYNTHETIC bilateral patient: one
// left-eye + one right-eye image of the same DR grade (laterality derived from
// anatomy — fovea temporal to disc). Each eye carries a `gt` payload (OD/fovea
// centres + FOV mask in DISPLAY-frame pixels); because the markers are in the
// displayed image's own frame, they overlay by simple scaling — no canonical
// flip / rotation / crop — which is exactly why they land correctly.
// ---------------------------------------------------------------------------
let lastIdridIdx = -1;
function pickRandomIdridPatient() {
  if (!IDRID_PATIENTS || IDRID_PATIENTS.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * IDRID_PATIENTS.length);
  } while (IDRID_PATIENTS.length > 1 && idx === lastIdridIdx);
  lastIdridIdx = idx;
  return IDRID_PATIENTS[idx];
}

// Build an eye-slot image object (with GT overlay payload) from a manifest eye.
function idridEyeImage(eye) {
  return {
    src: process.env.PUBLIC_URL + '/' + eye.image,
    name: eye.id,
    fromUpload: false,
    gt: {
      source: 'IDRiD',
      id: eye.id,
      side: eye.side,
      odCenter: eye.od_center,       // [x, y] in display-frame pixels
      foveaCenter: eye.fovea_center, // [x, y] in display-frame pixels
      odRadius: eye.od_radius,
      width: eye.width,
      height: eye.height,
      maskSrc: process.env.PUBLIC_URL + '/' + eye.mask,
    },
  };
}

// Walkthrough fallback (used only when IDRID_PATIENTS is empty).
let lastWalkIdx = -1;
function pickRandomWalkthrough(pool) {
  if (!pool || pool.length === 0) return null;
  let idx;
  do {
    idx = Math.floor(Math.random() * pool.length);
  } while (pool.length > 1 && idx === lastWalkIdx);
  lastWalkIdx = idx;
  return pool[idx];
}

// ---------------------------------------------------------------------------
// Simulated inference.
// Strategy: derive a deterministic pseudo-random seed from the image source
// (file name or sample URL). Match Config D's accuracy profile — pick the
// "true" class for samples (from /drN/ in the URL), or a uniform random class
// for arbitrary uploads. Add per-class softmax-like probabilities.
// ---------------------------------------------------------------------------
function hashStr(s) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h >>> 0;
}
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gradeFromUrl(url) {
  // Accepts legacy `dr0..dr4` (EyePACS samples + EyePACS pairs subfolders) and
  // zero-padded `dr00..dr04` (preprocessing-pipeline walkthrough images).
  const m = url && url.match(/\/dr0?([0-4])\//i);
  return m ? parseInt(m[1], 10) : null;
}

// Per-eye prediction. Mirrors Config-D: ~78% correct, ~17% off-by-one,
// ~5% off-by-two. Returns { pred, probs[5], confidence, trueGrade }.
function predictEye(src, key) {
  const seed = hashStr((src || '') + '|' + (key || ''));
  const rand = rng(seed);
  const truth = gradeFromUrl(src);
  // Use truth when available (sample image), else pick a class biased toward
  // lower grades (real-world prevalence-ish).
  const reference = truth !== null
    ? truth
    : [0, 0, 1, 2, 3, 4][Math.floor(rand() * 6)];

  // Decide outcome based on Config D weighted F1 (0.78).
  const r = rand();
  let pred;
  if (r < 0.78)       pred = reference;
  else if (r < 0.95)  pred = Math.max(0, Math.min(4, reference + (rand() < 0.5 ? -1 : 1)));
  else                pred = Math.max(0, Math.min(4, reference + (rand() < 0.5 ? -2 : 2)));

  // Build softmax-ish probabilities centered on `pred`.
  const raw = [0, 1, 2, 3, 4].map(c => {
    const dist = Math.abs(c - pred);
    return Math.exp(-1.4 * dist + (rand() - 0.5) * 0.4);
  });
  const sum = raw.reduce((a, b) => a + b, 0);
  const probs = raw.map(v => v / sum);
  return {
    pred,
    probs,
    confidence: probs[pred],
    trueGrade: truth,
    latencyMs: Math.round(180 + rand() * 220),
  };
}

// Patient-level result = worst eye (clinical convention for screening).
function patientPrediction(eyes) {
  // eyes: array of { eye, src } excluding empties
  const perEye = eyes.map(e => ({ ...e, result: predictEye(e.src, e.eye) }));
  if (perEye.length === 0) return null;
  const worst = perEye.reduce((a, b) => (b.result.pred > a.result.pred ? b : a));
  const probs = [0, 1, 2, 3, 4].map(c =>
    perEye.reduce((acc, p) => Math.max(acc, p.result.probs[c]), 0)
  );
  const sum = probs.reduce((a, b) => a + b, 0);
  const norm = probs.map(p => p / sum);
  return {
    perEye,
    pred: worst.result.pred,
    confidence: norm[worst.result.pred],
    probs: norm,
    latencyMs: Math.max(...perEye.map(p => p.result.latencyMs)),
  };
}

// Normalize the backend's PatientPredictionResponse (snake_case, no per-eye
// src) into the exact shape `patientPrediction` produces, so the Result panel
// renders identically whether the source is the real model or the simulator.
function normalizeApiResult(r, eyes) {
  return {
    pred: r.pred,
    probs: r.probs,
    confidence: r.confidence,
    latencyMs: r.latency_ms,
    perEye: (r.per_eye || []).map(p => ({
      eye: p.eye,
      src: (eyes.find(e => e.eye === p.eye) || {}).src,
      result: {
        pred: p.pred,
        probs: p.probs,
        confidence: p.confidence,
        latencyMs: p.latency_ms,
      },
    })),
  };
}

// ---------------------------------------------------------------------------
// UI sub-components
// ---------------------------------------------------------------------------
function EyeSlot({ label, eye, image, onPick, onClear, onSwap, t }) {
  const inputRef = useRef(null);
  const [dims, setDims] = useState(null);
  // "Keep" dismisses the wrong-slot warning for the current image only.
  const [dismissed, setDismissed] = useState(false);
  // Reset the size badge and dismissed-warning state when the loaded image
  // changes (or is cleared) so we never carry the previous image's dimensions
  // or a stale dismissal into a freshly loaded image. (Extracted to a variable
  // so react-hooks/exhaustive-deps can statically check it — a bare
  // `image && image.src` in the deps array trips the CI build under CI=1.)
  const imageSrc = image && image.src;
  useEffect(() => { setDims(null); setDismissed(false); }, [imageSrc]);

  const onChange = (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };
  const onDrop = (e) => {
    e.preventDefault();
    const file = e.dataTransfer.files && e.dataTransfer.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      const checks = await analyzeFundus(ev.target.result);
      onPick({ src: ev.target.result, name: file.name, fromUpload: true, checks });
    };
    reader.readAsDataURL(file);
  };

  // Derived check state for the chips below the preview.
  const checks = image && image.checks;
  const showNotFundus = !!(checks && checks.isFundus === false);
  const showWrongSide = !!(
    checks && checks.laterality && checks.laterality !== eye &&
    checks.confidence > 0.5 && !dismissed
  );
  const wrongSideMsg = showWrongSide
    ? t('demo.check.wrongSide').replace('{eye}', t('demo.check.eye.' + checks.laterality))
    : '';

  return (
    <div style={{ flex: 1, minWidth: 220 }}>
      <div style={{
        display: 'flex', alignItems: 'baseline', justifyContent: 'space-between',
        marginBottom: 6, gap: 6,
      }}>
        <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)' }}>
          {label}
        </div>
        {dims && (
          <div style={{
            fontSize: 9, fontFamily: 'monospace',
            color: 'var(--color-text-secondary,#888)',
          }}>
            {dims.w} × {dims.h} px
          </div>
        )}
      </div>
      <div
        onClick={() => inputRef.current && inputRef.current.click()}
        onDragOver={(e) => e.preventDefault()}
        onDrop={onDrop}
        style={{
          width: '100%',
          // Fixed 1:1 frame regardless of image presence — keeps the form
          // height stable so siblings (Run button, Result panel) don't jump
          // when an image loads or is cleared. Image is letterboxed inside.
          aspectRatio: '1 / 1',
          border: `1px dashed ${image ? C.teal : 'var(--color-border-secondary,#ccc)'}`,
          borderRadius: 10,
          background: image ? '#000' : 'var(--color-background-secondary,#f7f7f5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          cursor: 'pointer', overflow: 'hidden', position: 'relative',
        }}
      >
        {image ? (
          <img
            src={image.src}
            alt={label}
            onLoad={(e) => setDims({ w: e.target.naturalWidth, h: e.target.naturalHeight })}
            style={{
              width: '100%', height: '100%',
              objectFit: 'contain', display: 'block',
            }}
          />
        ) : (
          <div style={{ textAlign: 'center', color: 'var(--color-text-secondary,#888)', padding: 12 }}>
            <div style={{ fontSize: 11, fontWeight: 600 }}>{t('demo.dropHere')}</div>
            <div style={{ fontSize: 9, marginTop: 4 }}>{t('demo.formats')}</div>
          </div>
        )}
        <input ref={inputRef} type="file" accept="image/*" onChange={onChange} style={{ display: 'none' }} />
      </div>

      {/* Validation chips (uploaded images only). Warn, never block. */}
      {showNotFundus && (
        <div style={{
          marginTop: 6, padding: '4px 8px', borderRadius: 4, fontSize: 10,
          background: C.amberBg, color: C.amberT, border: `1px solid ${C.amber}`,
        }}>
          ⚠ {t('demo.check.notFundus')}
        </div>
      )}
      {showWrongSide && (
        <div style={{
          marginTop: 6, padding: '6px 8px', borderRadius: 4, fontSize: 10,
          background: C.redBg, color: C.redT, border: `1px solid ${C.red}`,
          display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap',
        }}>
          <span style={{ flex: 1, minWidth: 120 }}>⚠ {wrongSideMsg}</span>
          <button
            onClick={onSwap}
            style={{
              padding: '2px 8px', fontSize: 10, fontWeight: 600,
              background: C.red, color: 'white', border: 'none',
              borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.swap')}
          </button>
          <button
            onClick={() => setDismissed(true)}
            style={{
              padding: '2px 8px', fontSize: 10,
              background: 'transparent', color: C.redT,
              border: `1px solid ${C.red}`, borderRadius: 3, cursor: 'pointer',
            }}
          >
            {t('demo.check.keep')}
          </button>
        </div>
      )}
      {/* Always reserve the Clear button's vertical space so the form height
          doesn't change when an image is added/removed. The button is only
          visible (and clickable) when there is something to clear. */}
      <button
        onClick={onClear}
        disabled={!image}
        style={{
          marginTop: 6, fontSize: 10, padding: '3px 8px', background: 'transparent',
          color: C.red, border: `1px solid ${C.red}`, borderRadius: 4,
          cursor: image ? 'pointer' : 'default',
          visibility: image ? 'visible' : 'hidden',
        }}
      >
        {t('demo.clear')}
      </button>
    </div>
  );
}

function ProbabilityBar({ idx, p, isPred, t }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
      <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', minWidth: 36, fontWeight: isPred ? 700 : 400 }}>
        {t('demo.gradeShort.' + idx)}
      </div>
      <div style={{ flex: 1, height: 16, background: 'var(--color-background-secondary,#eeede9)', borderRadius: 3, position: 'relative', overflow: 'hidden' }}>
        <div style={{ width: `${p * 100}%`, height: '100%', background: isPred ? C.teal : C.gray, opacity: isPred ? 0.85 : 0.45 }} />
        <span style={{ position: 'absolute', right: 5, top: '50%', transform: 'translateY(-50%)', fontSize: 9, fontWeight: isPred ? 700 : 500, color: 'var(--color-text-primary,#333)' }}>
          {(p * 100).toFixed(1)}%
        </span>
      </div>
    </div>
  );
}

function HeatmapPair({ resultsBase, side, t }) {
  const base = process.env.PUBLIC_URL + '/' + resultsBase;
  return (
    <div style={{ flex: 1, minWidth: 220 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t(side === 'left' ? 'demo.leftEye' : 'demo.rightEye')}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 6 }}>
        <figure style={{ margin: 0 }}>
          <img
            src={`${base}/gradcam/${side}.png`}
            alt={`Grad-CAM ${side}`}
            style={{ width: '100%', display: 'block', borderRadius: 6, background: '#000' }}
          />
          <figcaption style={{ fontSize: 10, marginTop: 4, color: 'var(--color-text-secondary,#666)' }}>
            {t('demo.viz.gradcam')}
          </figcaption>
        </figure>
        <figure style={{ margin: 0 }}>
          <img
            src={`${base}/attention_overlay/${side}.png`}
            alt={`Attention overlay ${side}`}
            style={{ width: '100%', display: 'block', borderRadius: 6, background: '#000' }}
          />
          <figcaption style={{ fontSize: 10, marginTop: 4, color: 'var(--color-text-secondary,#666)' }}>
            {t('demo.viz.overlay')}
          </figcaption>
        </figure>
      </div>
    </div>
  );
}

function VisualizationBlock({ caseRef, leftPresent, rightPresent, t }) {
  const explainable = caseRef && caseRef.explainable && caseRef.resultsBase;
  return (
    <div style={{ marginTop: 14 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
        {t('demo.viz.title')}
      </div>
      {explainable ? (
        <>
          <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
            {leftPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="left" t={t} />}
            {rightPresent && <HeatmapPair resultsBase={caseRef.resultsBase} side="right" t={t} />}
          </div>
          <Note>{t('demo.viz.disclaimer')}</Note>
        </>
      ) : (
        <Note>{t('demo.viz.unavailable')}</Note>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------
// Access-password screen (TASK-Demo §C.2). Shown only when the backend reports
// `requires_password` and no valid password is held yet. A single input — no
// accounts, no login flow — adequate for a ~15-person academic beta.
function PasswordGate({ onUnlock, t }) {
  const [pw, setPw] = useState('');
  const [status, setStatus] = useState('idle'); // idle | checking | denied
  const submit = async () => {
    if (!pw || status === 'checking') return;
    setStatus('checking');
    try {
      const ok = await verifyPassword(pw);
      if (ok) {
        setPassword(pw);          // persist for subsequent protected requests
        onUnlock();
      } else {
        setStatus('denied');
      }
    } catch {
      // Network error reaching the backend — treat as denied but distinct copy.
      setStatus('denied');
    }
  };
  return (
    <div style={{ maxWidth: 380, margin: '40px auto', textAlign: 'center' }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, color: 'var(--color-text-primary,#222)', marginBottom: 6 }}>
        {t('demo.gate.title')}
      </h2>
      <p style={{ fontSize: 12, color: 'var(--color-text-secondary,#666)', lineHeight: 1.55, marginBottom: 14 }}>
        {t('demo.gate.prompt')}
      </p>
      <input
        type="password"
        value={pw}
        autoFocus
        onChange={(e) => { setPw(e.target.value); if (status === 'denied') setStatus('idle'); }}
        onKeyDown={(e) => { if (e.key === 'Enter') submit(); }}
        placeholder={t('demo.gate.placeholder')}
        style={{
          width: '100%', padding: '8px 12px', fontSize: 13, boxSizing: 'border-box',
          border: `1px solid ${status === 'denied' ? C.red : 'var(--color-border-secondary,#ccc)'}`,
          borderRadius: 6, marginBottom: 10,
        }}
      />
      <button
        onClick={submit}
        disabled={!pw || status === 'checking'}
        style={{
          width: '100%', padding: '8px 18px', fontSize: 12, fontWeight: 600,
          background: (!pw || status === 'checking') ? C.gray : C.teal,
          color: 'white', border: 'none', borderRadius: 6,
          cursor: (!pw || status === 'checking') ? 'not-allowed' : 'pointer',
        }}
      >
        {status === 'checking' ? t('demo.gate.checking') : t('demo.gate.submit')}
      </button>
      {status === 'denied' && (
        <div style={{ marginTop: 10, fontSize: 11, color: C.redT }}>
          {t('demo.gate.denied')}
        </div>
      )}
    </div>
  );
}

export default function Demo() {
  const { t } = useLang();
  const [leftImg, setLeftImg] = useState(null);
  const [rightImg, setRightImg] = useState(null);
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState(null);
  const [feedbackMode, setFeedbackMode] = useState(null); // 'confirm' | 'reject' | null
  const [correctedGrade, setCorrectedGrade] = useState(0);
  const [toast, setToast] = useState('');
  const [history, setHistory] = useState([]);
  // Tracks the active sample case (from WALKTHROUGH_POOL) so the result
  // panel can show pre-generated Grad-CAM + attention overlay. Any manual
  // upload or per-eye clear resets this to null — we cannot show heatmaps
  // for images that don't have a pre-generated companion under
  // `pipeline/dr0N/results/`.
  const [caseRef, setCaseRef] = useState(null);
  // Backend health. `health` is the /api/health payload (or null when the
  // backend is unreachable). `healthChecked` flips once the probe resolves so
  // the badge can show a "checking…" state in between. `useRealModel` lets the
  // user force the offline simulator even when the backend is up.
  const [health, setHealth] = useState(null);
  const [healthChecked, setHealthChecked] = useState(false);
  const [useRealModel, setUseRealModel] = useState(true);
  // Access gate (TASK-Demo §C.2/D). `authed` is true when the demo body is
  // unlocked: either the backend reports no password requirement / is offline
  // (simulator stays usable), or the user has supplied a valid password (which
  // we also revalidate from sessionStorage on reload).
  const [authed, setAuthed] = useState(false);
  useEffect(() => {
    let alive = true;
    getHealth().then(async (h) => {
      if (!alive) return;
      setHealth(h);
      setHealthChecked(true);
      // No live gate to satisfy → unlock immediately (offline demo included).
      if (!h || !h.requires_password) { setAuthed(true); return; }
      // Gate active: try a previously stored password silently.
      const stored = getPassword();
      if (stored) {
        try { if (await verifyPassword(stored)) setAuthed(true); } catch { /* offline */ }
      }
    });
    return () => { alive = false; };
  }, []);
  // Real model is usable only when the backend is up AND a real checkpoint is
  // loaded (a boot without a checkpoint runs on random weights — meaningless,
  // so we stay on the simulator and say so).
  const apiReady = !!(health && health.checkpoint_loaded) && useRealModel;
  // Preprocessing visualizations (/api/visualize, /api/gradcam) only need the
  // backend reachable — /api/visualize is checkpoint-free, so the "what the
  // model sees" widget lights up even before Config D is trained.
  const liveVisuals = !!health && useRealModel;

  const D = CONFIGS.D;

  const eyes = useMemo(() => {
    const list = [];
    if (leftImg)  list.push({ eye: 'left',  src: leftImg.src,  name: leftImg.name  || 'left'  });
    if (rightImg) list.push({ eye: 'right', src: rightImg.src, name: rightImg.name || 'right' });
    return list;
  }, [leftImg, rightImg]);

  // Swap the two slots — used by the wrong-slot warning chip. Both images
  // (with their attached `checks`) move to the opposite slot; the laterality
  // check then re-evaluates against the new slot and the warning clears.
  const swapSlots = () => {
    setLeftImg(rightImg);
    setRightImg(leftImg);
    setResult(null);
    setFeedbackMode(null);
  };

  const reset = (keepHistory = true) => {
    setLeftImg(null);
    setRightImg(null);
    setCaseRef(null);
    setResult(null);
    setFeedbackMode(null);
    setCorrectedGrade(0);
    if (!keepHistory) setHistory([]);
  };

  const handleRun = async () => {
    if (eyes.length === 0) return;
    setRunning(true);
    setResult(null);
    setFeedbackMode(null);

    if (apiReady) {
      try {
        const r = await predictPatient(eyes);
        setResult(normalizeApiResult(r, eyes));
      } catch (e) {
        console.error(e);
        setToast(t('demo.modelStatus.fallbackToast'));
        setTimeout(() => setToast(''), 4000);
        setResult(patientPrediction(eyes)); // graceful fallback
      } finally {
        setRunning(false);
      }
      return;
    }

    // Simulator path — keep a small latency so the UI feels realistic.
    setTimeout(() => {
      setResult(patientPrediction(eyes));
      setRunning(false);
    }, 700);
  };

  // Pick handler for an eye slot. On a manual upload we also try to match the
  // file against IDRiD localization ground truth by filename (IDRiD_NNN); if it
  // matches, we attach the `gt` payload so the preprocessing/centre overlay
  // renders for it (the overlay only shows for GT-backed images).
  const handlePick = (setImg) => (img) => {
    setImg(img);
    if (img && img.fromUpload) {
      setCaseRef(null);
      matchIdridUpload(img.name, img.src).then((gt) => {
        if (gt) setImg((cur) => (cur && cur.src === img.src ? { ...cur, gt } : cur));
      });
    }
  };

  // Roll a random IDRiD patient (one left + one right eye, same DR grade), each
  // carrying ground-truth OD + fovea centres. The left-anatomy image goes to the
  // LEFT slot and the right-anatomy image to the RIGHT slot, so both eyes show
  // GT markers VisionWidget overlays directly. If the IDRiD manifest is empty
  // (prep script not yet run), fall back to a walkthrough bilateral case.
  const loadRandomSample = () => {
    const patient = pickRandomIdridPatient();
    if (patient) {
      setLeftImg(idridEyeImage(patient.left));
      setRightImg(idridEyeImage(patient.right));
      setCaseRef(null); // IDRiD samples have no pre-rendered explainability assets
    } else {
      const w = pickRandomWalkthrough(WALKTHROUGH_POOL);
      if (!w) return;
      setLeftImg({  src: process.env.PUBLIC_URL + '/' + w.left,  name: w.left,  fromUpload: false });
      setRightImg({ src: process.env.PUBLIC_URL + '/' + w.right, name: w.right, fromUpload: false });
      setCaseRef(w);
    }
    setResult(null);
    setFeedbackMode(null);
  };

  const submitFeedback = (verdict) => {
    if (!result) return;
    const entry = {
      id: Date.now(),
      timestamp: new Date().toISOString(),
      images: eyes.map(e => ({ eye: e.eye, source: e.name })),
      predicted: result.pred,
      confidence: Number(result.confidence.toFixed(4)),
      probs: result.probs.map(p => Number(p.toFixed(4))),
      verdict,
      corrected_grade: verdict === 'confirmed' ? result.pred : correctedGrade,
      latency_ms: result.latencyMs,
      model: 'config-D (pipeline + EfficientNet-B3)',
    };
    setHistory(h => [entry, ...h]);
    setToast(t('demo.thanks'));
    setTimeout(() => setToast(''), 2500);
    setFeedbackMode(null);
  };

  const exportJsonl = () => {
    if (history.length === 0) return;
    const jsonl = history.map(h => JSON.stringify(h)).join('\n');
    const blob = new Blob([jsonl], { type: 'application/x-ndjson' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dr-relabel-${new Date().toISOString().replace(/[:.]/g, '-')}.jsonl`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Block the demo body behind the access screen only when the backend
  // actively requires a password and we are not yet authenticated. A null/
  // offline health never gates — the simulator must stay reachable.
  if (healthChecked && health && health.requires_password && !authed) {
    return <PasswordGate onUnlock={() => setAuthed(true)} t={t} />;
  }

  return (
    <div>
      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--color-text-primary,#222)', margin: '0 0 4px 0' }}>
          {t('demo.title')}
        </h2>
        <p style={{ fontSize: 12, color: 'var(--color-text-secondary,#666)', margin: '0 0 8px 0', lineHeight: 1.55 }}>
          {t('demo.subtitle')}
        </p>
        {/* Framing block (TASK-Demo D.1) — muted, no marketing copy. */}
        <div style={{
          fontSize: 11, color: 'var(--color-text-secondary,#777)', lineHeight: 1.6,
          borderLeft: `2px solid ${C.teal}`, paddingLeft: 10, margin: '0 0 8px 0',
        }}>
          <div style={{ fontWeight: 700 }}>{t('demo.framing.line1')}</div>
          <div>{t('demo.framing.line2')}</div>
          <div>{t('demo.framing.line3')}</div>
        </div>
        {/* <div style={{ fontSize: 10, color: C.amberT, background: C.amberBg, padding: '6px 10px', borderRadius: 6, display: 'inline-block' }}>
          ⚠ {t('demo.disclaimer')}
        </div> */}
      </div>

      {/* Upload section */}
      <Sec title={t('demo.uploadSection')}>
        <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
          <EyeSlot
            label={t('demo.leftEye')}
            eye="left"
            image={leftImg}
            onPick={handlePick(setLeftImg)}
            onClear={() => { setLeftImg(null); setCaseRef(null); setResult(null); setFeedbackMode(null); }}
            onSwap={swapSlots}
            t={t}
          />
          <EyeSlot
            label={t('demo.rightEye')}
            eye="right"
            image={rightImg}
            onPick={handlePick(setRightImg)}
            onClear={() => { setRightImg(null); setCaseRef(null); setResult(null); setFeedbackMode(null); }}
            onSwap={swapSlots}
            t={t}
          />
        </div>

        {/* Per-image "what the model sees" widget (TASK-Demo D.2). Shown ONLY
            for ground-truth-backed images — i.e. the Random IDRiD button, or a
            manual upload matched to IDRiD by filename. The preprocessing strip
            still needs the backend (best-effort); markers/mask come from GT and
            render even offline. */}
        {(leftImg?.gt || rightImg?.gt) && (
          <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap', marginTop: 12 }}>
            {leftImg?.gt && (
              <VisionWidget src={leftImg.src} eye="left" name={leftImg.name} enabled={liveVisuals} gt={leftImg.gt} t={t} />
            )}
            {rightImg?.gt && (
              <VisionWidget src={rightImg.src} eye="right" name={rightImg.name} enabled={liveVisuals} gt={rightImg.gt} t={t} />
            )}
          </div>
        )}

        {/* Detector path: for non-GT uploads, show the learned OD/fovea overlay
            (probability discs + heatmap) and let the clinician drag-correct the
            centres (Phase 3 feedback loop). Needs the live backend (liveVisuals). */}
        {liveVisuals && ((leftImg && !leftImg.gt) || (rightImg && !rightImg.gt)) && (
          <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap', marginTop: 12 }}>
            {leftImg && !leftImg.gt && (
              <VisionWidget src={leftImg.src} eye="left" name={leftImg.name} enabled={liveVisuals} t={t} />
            )}
            {rightImg && !rightImg.gt && (
              <VisionWidget src={rightImg.src} eye="right" name={rightImg.name} enabled={liveVisuals} t={t} />
            )}
          </div>
        )}

        <div style={{ marginTop: 14 }}>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            <button
              onClick={loadRandomSample}
              title={t('demo.randomHint')}
              style={{
                padding: '4px 10px', fontSize: 10, fontWeight: 600,
                background: C.purpleBg, color: C.purpleT,
                border: `1px solid ${C.purple}`, borderRadius: 4, cursor: 'pointer',
              }}
            >
              🎲 {t('demo.random')}
              {IDRID_PATIENTS && IDRID_PATIENTS.length > 0 && (
                <span style={{ marginLeft: 4, opacity: 0.6, fontWeight: 400 }}>
                  IDRiD ({IDRID_PATIENTS.length})
                </span>
              )}
            </button>
          </div>
          <Note>{t('demo.randomHint')}</Note>
        </div>
      </Sec>

      {/* Run section */}
      <Sec title={t('demo.runSection')}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
          <button
            onClick={handleRun}
            disabled={running || eyes.length === 0}
            style={{
              padding: '8px 18px', fontSize: 12, fontWeight: 600,
              background: (running || eyes.length === 0) ? C.gray : C.teal,
              color: 'white', border: 'none', borderRadius: 6,
              cursor: (running || eyes.length === 0) ? 'not-allowed' : 'pointer',
            }}
          >
            {running ? t('demo.running') : t('demo.runButton')}
          </button>
          {eyes.length === 0 && (
            <span style={{ fontSize: 11, color: C.red }}>{t('demo.needAtLeastOne')}</span>
          )}
          {eyes.length > 0 && !running && (
            <span style={{ fontSize: 11, color: 'var(--color-text-secondary,#666)' }}>
              {eyes.length} {eyes.length === 1 ? 'image' : 'images'} · {t('demo.modelVersion')}: Config D
            </span>
          )}
          {/* Model status badge: checking → real → simulator. */}
          <span style={{
            fontSize: 10, fontWeight: 600,
            color: !healthChecked ? C.gray : (apiReady ? C.greenT : C.amberT),
          }}>
            {!healthChecked
              ? t('demo.modelStatus.checking')
              : apiReady ? t('demo.modelStatus.real') : t('demo.modelStatus.simulator')}
          </span>
          {/* Toggle real/simulator — only when a real checkpoint is actually loaded. */}
          {health && health.checkpoint_loaded && (
            <button
              onClick={() => setUseRealModel(v => !v)}
              style={{
                fontSize: 10, padding: '2px 8px', background: 'transparent',
                color: 'var(--color-text-secondary,#666)',
                border: '1px solid var(--color-border-secondary,#ccc)',
                borderRadius: 4, cursor: 'pointer',
              }}
            >
              {useRealModel ? t('demo.modelStatus.useSimulator') : t('demo.modelStatus.useReal')}
            </button>
          )}
        </div>
      </Sec>

      {/* Result section */}
      {result && (
        <Sec title={t('demo.resultSection')}>
          <div style={{
            display: 'flex', gap: 12, flexWrap: 'wrap',
            padding: 14, borderRadius: 10,
            background: result.pred >= 2 ? C.coralBg : C.tealBg,
            border: `1px solid ${result.pred >= 2 ? C.coral : C.teal}`,
          }}>
            <div style={{ flex: 1, minWidth: 180 }}>
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: result.pred >= 2 ? C.coralT : C.tealT, opacity: 0.8 }}>
                {t('demo.predictedGrade')}
              </div>
              <div style={{ fontSize: 22, fontWeight: 700, color: result.pred >= 2 ? C.coralT : C.tealT, marginTop: 2 }}>
                {t('demo.grade.' + result.pred)}
              </div>
              <div style={{ fontSize: 11, color: 'var(--color-text-secondary,#555)', marginTop: 6 }}>
                {t('demo.confidence')}: <strong>{(result.confidence * 100).toFixed(1)}%</strong>
                {' · '}
                {t('demo.referable')}: <strong>{result.pred >= 2 ? t('demo.yes') : t('demo.no')}</strong>
                {' · '}
                {t('demo.latency')}: <strong>{result.latencyMs} ms</strong>
              </div>
            </div>
            <div style={{ flex: 1, minWidth: 220 }}>
              <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 4 }}>
                {t('demo.classProbs')}
              </div>
              {result.probs.map((p, i) => (
                <ProbabilityBar key={i} idx={i} p={p} isPred={i === result.pred} t={t} />
              ))}
            </div>
          </div>

          {/* Per-eye breakdown */}
          {result.perEye.length > 1 && (
            <div style={{ marginTop: 12 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-text-secondary,#666)', marginBottom: 6 }}>
                {t('demo.perEye')}
              </div>
              <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                {result.perEye.map((eye, i) => (
                  <div key={i} style={{
                    flex: 1, minWidth: 200, padding: '8px 12px',
                    background: 'var(--color-background-secondary,#f7f7f5)', borderRadius: 8,
                    borderLeft: `3px solid ${eye.result.pred >= 2 ? C.coral : C.teal}`,
                  }}>
                    <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', fontWeight: 600 }}>
                      {t(eye.eye === 'left' ? 'demo.leftEye' : 'demo.rightEye')}
                    </div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--color-text-primary,#222)' }}>
                      {t('demo.grade.' + eye.result.pred)}
                    </div>
                    <div style={{ fontSize: 10, color: 'var(--color-text-secondary,#666)', marginTop: 2 }}>
                      {(eye.result.confidence * 100).toFixed(1)}% · {eye.result.latencyMs} ms
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Grad-CAM heatmap + attention overlay.
              Live (from the checkpoint) for custom uploads when the real model
              is active; pre-rendered walkthrough assets otherwise. */}
          {apiReady && caseRef === null && eyes.length > 0 ? (
            <LiveVisualizationBlock eyes={eyes} t={t} />
          ) : (
            <VisualizationBlock
              caseRef={caseRef}
              leftPresent={!!leftImg}
              rightPresent={!!rightImg}
              t={t}
            />
          )}
        </Sec>
      )}

      {/* Feedback section */}
      {result && (
        <Sec title={t('demo.feedbackSection')} note={t('demo.feedbackHint')}>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'center' }}>
            <button
              onClick={() => { setFeedbackMode('confirm'); submitFeedback('confirmed'); }}
              style={{
                padding: '8px 16px', fontSize: 12, fontWeight: 600,
                background: C.green, color: 'white', border: 'none',
                borderRadius: 6, cursor: 'pointer',
              }}
            >
              ✓ {t('demo.confirm')}
            </button>
            <button
              onClick={() => setFeedbackMode('reject')}
              style={{
                padding: '8px 16px', fontSize: 12, fontWeight: 600,
                background: 'white', color: C.red,
                border: `1px solid ${C.red}`, borderRadius: 6, cursor: 'pointer',
              }}
            >
              ✕ {t('demo.reject')}
            </button>
          </div>
          {feedbackMode === 'reject' && (
            <div style={{
              marginTop: 12, padding: 12, borderRadius: 8,
              background: C.redBg, border: `1px solid ${C.red}`,
              display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap',
            }}>
              <label style={{ fontSize: 11, fontWeight: 600, color: C.redT }}>
                {t('demo.correctGrade')}:
              </label>
              <select
                value={correctedGrade}
                onChange={(e) => setCorrectedGrade(parseInt(e.target.value, 10))}
                style={{ padding: '4px 8px', fontSize: 11, border: '1px solid var(--color-border-secondary,#ccc)', borderRadius: 4 }}
              >
                {[0, 1, 2, 3, 4].map(g => (
                  <option key={g} value={g}>{t('demo.grade.' + g)}</option>
                ))}
              </select>
              <button
                onClick={() => submitFeedback('rejected')}
                style={{
                  padding: '6px 14px', fontSize: 11, fontWeight: 600,
                  background: C.red, color: 'white', border: 'none',
                  borderRadius: 4, cursor: 'pointer',
                }}
              >
                {t('demo.submit')}
              </button>
            </div>
          )}
          {toast && (
            <div style={{
              marginTop: 10, padding: '8px 12px', borderRadius: 6,
              background: C.greenBg, color: C.greenT, fontSize: 11, fontWeight: 600,
            }}>
              ✓ {toast}
            </div>
          )}
        </Sec>
      )}

      {/* History / relabeling buffer */}
      <Sec title={`${t('demo.historyTitle')} (${history.length})`}>
        <div style={{ display: 'flex', gap: 8, marginBottom: 10 }}>
          <button
            onClick={exportJsonl}
            disabled={history.length === 0}
            style={{
              padding: '6px 12px', fontSize: 11, fontWeight: 600,
              background: history.length === 0 ? C.gray : C.blue,
              color: 'white', border: 'none', borderRadius: 4,
              cursor: history.length === 0 ? 'not-allowed' : 'pointer',
            }}
          >
            ⬇ {t('demo.export')}
          </button>
          <button
            onClick={() => setHistory([])}
            disabled={history.length === 0}
            style={{
              padding: '6px 12px', fontSize: 11,
              background: 'white', color: history.length === 0 ? C.gray : C.red,
              border: `1px solid ${history.length === 0 ? C.gray : C.red}`,
              borderRadius: 4, cursor: history.length === 0 ? 'not-allowed' : 'pointer',
            }}
          >
            {t('demo.clearAll')}
          </button>
        </div>
        {history.length === 0 ? (
          <Note>{t('demo.historyEmpty')}</Note>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--color-border-secondary,#ccc)' }}>
                  <th style={{ padding: '5px 8px', textAlign: 'left', fontWeight: 600 }}>{t('demo.col.time')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.images')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.predicted')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.verdict')}</th>
                  <th style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>{t('demo.col.corrected')}</th>
                </tr>
              </thead>
              <tbody>
                {history.map(h => (
                  <tr key={h.id} style={{ borderBottom: '1px solid var(--color-border-tertiary,#eee)' }}>
                    <td style={{ padding: '5px 8px', fontFamily: 'monospace', fontSize: 10, color: 'var(--color-text-secondary,#666)' }}>
                      {new Date(h.timestamp).toLocaleTimeString()}
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>{h.images.length}</td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.predicted)} ({(h.confidence * 100).toFixed(0)}%)
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center' }}>
                      <span style={{
                        padding: '2px 6px', borderRadius: 3, fontSize: 10, fontWeight: 600,
                        background: h.verdict === 'confirmed' ? C.greenBg : C.redBg,
                        color: h.verdict === 'confirmed' ? C.greenT : C.redT,
                      }}>
                        {t('demo.verdict.' + h.verdict)}
                      </span>
                    </td>
                    <td style={{ padding: '5px 8px', textAlign: 'center', fontWeight: 600 }}>
                      {t('demo.gradeShort.' + h.corrected_grade)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Sec>

      {/* Footer caveat — reflects whether predictions are live or simulated. */}
      <Note>
        {apiReady ? t('demo.modelStatus.footerReal') : t('demo.modelStatus.footerSim')}
        {' '}Reference metrics on held-out EyePACS: F1={D.f1.toFixed(3)}, AUC={D.auc.toFixed(3)}, κ={D.k.toFixed(3)}.
      </Note>
      {/* Provenance string (TASK-Demo D.7) — what the committee can quote. */}
      {health && (
        <div style={{ fontSize: 9, color: C.gray, marginTop: 4, fontFamily: 'monospace' }}>
          version {health.version} · git {health.git_sha || 'n/a'} · checkpoint {health.checkpoint}
          {health.checkpoint_loaded ? '' : ' (not loaded)'} · {health.device}
        </div>
      )}

      <div style={{ marginTop: 14 }}>
        <button onClick={() => reset(true)} style={{
          fontSize: 10, padding: '4px 10px', background: 'transparent',
          color: 'var(--color-text-secondary,#666)',
          border: '1px solid var(--color-border-secondary,#ccc)',
          borderRadius: 4, cursor: 'pointer',
        }}>
          ↺ Reset case
        </button>
      </div>
    </div>
  );
}
