// Auto-generated by demo/scripts/prepare_eyepacs_pairs.py.
// Edit the script and re-run; do not modify this file by hand.
// Source: EyePACS / Kaggle Diabetic Retinopathy Detection.
// 40 bilateral patient pairs.

export const EYEPACS_PAIRS = [
  {
    "patient_id": "10",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/10_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/10_right.jpeg"
  },
  {
    "patient_id": "13",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/13_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/13_right.jpeg"
  },
  {
    "patient_id": "19",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/19_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/19_right.jpeg"
  },
  {
    "patient_id": "20",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/20_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/20_right.jpeg"
  },
  {
    "patient_id": "21",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/21_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/21_right.jpeg"
  },
  {
    "patient_id": "22",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/22_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/22_right.jpeg"
  },
  {
    "patient_id": "23",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/23_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/23_right.jpeg"
  },
  {
    "patient_id": "25",
    "worst_grade": 0,
    "left_grade": 0,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr0/25_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr0/25_right.jpeg"
  },
  {
    "patient_id": "17",
    "worst_grade": 1,
    "left_grade": 0,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/17_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/17_right.jpeg"
  },
  {
    "patient_id": "36",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr1/36_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/36_right.jpeg"
  },
  {
    "patient_id": "204",
    "worst_grade": 1,
    "left_grade": 0,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/204_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/204_right.jpeg"
  },
  {
    "patient_id": "214",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr1/214_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/214_right.jpeg"
  },
  {
    "patient_id": "114",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/114_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/114_right.jpeg"
  },
  {
    "patient_id": "178",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/178_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/178_right.jpeg"
  },
  {
    "patient_id": "348",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/348_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/348_right.jpeg"
  },
  {
    "patient_id": "417",
    "worst_grade": 1,
    "left_grade": 1,
    "right_grade": 1,
    "left": "datasets/eyepacs/pairs/dr1/417_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr1/417_right.jpeg"
  },
  {
    "patient_id": "15",
    "worst_grade": 2,
    "left_grade": 1,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/15_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/15_right.jpeg"
  },
  {
    "patient_id": "30",
    "worst_grade": 2,
    "left_grade": 1,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/30_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/30_right.jpeg"
  },
  {
    "patient_id": "40",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr2/40_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/40_right.jpeg"
  },
  {
    "patient_id": "51",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 0,
    "left": "datasets/eyepacs/pairs/dr2/51_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/51_right.jpeg"
  },
  {
    "patient_id": "54",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/54_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/54_right.jpeg"
  },
  {
    "patient_id": "78",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/78_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/78_right.jpeg"
  },
  {
    "patient_id": "79",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/79_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/79_right.jpeg"
  },
  {
    "patient_id": "82",
    "worst_grade": 2,
    "left_grade": 2,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr2/82_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr2/82_right.jpeg"
  },
  {
    "patient_id": "328",
    "worst_grade": 3,
    "left_grade": 2,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/328_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/328_right.jpeg"
  },
  {
    "patient_id": "391",
    "worst_grade": 3,
    "left_grade": 2,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/391_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/391_right.jpeg"
  },
  {
    "patient_id": "509",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr3/509_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/509_right.jpeg"
  },
  {
    "patient_id": "609",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr3/609_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/609_right.jpeg"
  },
  {
    "patient_id": "99",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/99_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/99_right.jpeg"
  },
  {
    "patient_id": "163",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/163_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/163_right.jpeg"
  },
  {
    "patient_id": "352",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/352_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/352_right.jpeg"
  },
  {
    "patient_id": "531",
    "worst_grade": 3,
    "left_grade": 3,
    "right_grade": 3,
    "left": "datasets/eyepacs/pairs/dr3/531_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr3/531_right.jpeg"
  },
  {
    "patient_id": "439",
    "worst_grade": 4,
    "left_grade": 2,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/439_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/439_right.jpeg"
  },
  {
    "patient_id": "458",
    "worst_grade": 4,
    "left_grade": 3,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/458_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/458_right.jpeg"
  },
  {
    "patient_id": "986",
    "worst_grade": 4,
    "left_grade": 4,
    "right_grade": 2,
    "left": "datasets/eyepacs/pairs/dr4/986_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/986_right.jpeg"
  },
  {
    "patient_id": "1099",
    "worst_grade": 4,
    "left_grade": 3,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/1099_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/1099_right.jpeg"
  },
  {
    "patient_id": "16",
    "worst_grade": 4,
    "left_grade": 4,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/16_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/16_right.jpeg"
  },
  {
    "patient_id": "217",
    "worst_grade": 4,
    "left_grade": 4,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/217_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/217_right.jpeg"
  },
  {
    "patient_id": "294",
    "worst_grade": 4,
    "left_grade": 4,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/294_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/294_right.jpeg"
  },
  {
    "patient_id": "326",
    "worst_grade": 4,
    "left_grade": 4,
    "right_grade": 4,
    "left": "datasets/eyepacs/pairs/dr4/326_left.jpeg",
    "right": "datasets/eyepacs/pairs/dr4/326_right.jpeg"
  }
];
